# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-10-22 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flower_name', models.CharField(max_length=250)),
                ('flower_image', models.CharField(max_length=1000)),
            ],
        ),
    ]
