# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-10-23 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identify', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flower',
            name='flower_image',
            field=models.FileField(upload_to=''),
        ),
    ]
